services:
  db:
    image: postgres:14-alpine
    container_name: coffeenet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    restart: unless-stopped

  ia_1_nlu:
    container_name: coffeenet_ia_1
    build:
      context: ./ia_1_nlu
    restart: unless-stopped

  backend:
    container_name: coffeenet_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - ia_1_nlu
    restart: unless-stopped

volumes:
  postgres_data:
